INSERT INTO correlativos.correlativos (nombre_documento,abreviatura,descripcion) VALUES
	 ('COMPROBANTE DE DIARIO','CD','REGISTRO DE TODOS LOS INGRESOS Y EGRESOS EFECTUADOS POR LA EMPRESA , EN EL ORDEN QUE SE VAYA REALIZANDO DURANTE EL PERÍODO (TRANSFERENCIAS,PAGOS,COBROS,GASTOS,OTROS)'),
	 ('COMPROGANTE DE TRASPASO','TR','NO REGISTRA INGRESOS NI EGRESOS DE FONDOS, SINO EL MOVIMIENTO DE LOS RECURSOS DE LA EMPRESA.'),
	 ('COMPROBANTE DE GASTO','GA',NULL),
	 ('COMPROBANTE DE INGRESO','IN',NULL);



INSERT INTO correlativos.correlativos_entidad_gestion (id_correlativo,id_entidad,id_dependencia,gestion) VALUES
	 (1,1,2,2025),
	 (2,1,2,2025),
	 (3,1,2,2025),
	 (4,1,2,2025);


INSERT INTO administracion.dominios (concepto,descripcion,valor1,valor2,orden) VALUES
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','ACT','ACTIVO',1),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','HI','HISTORICO',2),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','ANU','ANULADO',3),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','BAJ','BAJA',4),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','CON','CONFIRMADO',5),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','PEN','PENDIENTE',6),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','REV','REVISADO',7),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','VER','VERIFICADO',8),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','INI','INICIADO',9),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','CNS','CONSOLIDADO',10),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','REC','RECHAZADO',11),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','ESP','EN ESPERA',12),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','PRO','PROCESADO',13),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','EX','EXPIRADO',14),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','RES','RESETEADO',15),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','RCD','RECEPCIONADO',16),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','CER','CERTIFICADO',17),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','ELI','ELIMINADO',18),
	 ('ESTADO REGISTRO','TIPOS DE ESTADO DE LOS REGISTROS','ARC','ARCHIVADO',19),
	 ('MESES','DESCRIPCION MESES','1','ENERO',1),
	 ('MESES','DESCRIPCION MESES','2','FEBRERO',2),
	 ('MESES','DESCRIPCION MESES','3','MARZO',3),
	 ('MESES','DESCRIPCION MESES','4','ABRIL',4),
	 ('MESES','DESCRIPCION MESES','5','MAYO',5),
	 ('MESES','DESCRIPCION MESES','6','JUNIO',6),
	 ('MESES','DESCRIPCION MESES','7','JULIO',7),
	 ('MESES','DESCRIPCION MESES','8','AGOSTO',8),
	 ('MESES','DESCRIPCION MESES','9','SEPTIEMBRE',9),
	 ('MESES','DESCRIPCION MESES','10','OCTUBRE',10),
	 ('MESES','DESCRIPCION MESES','11','NOVIEMBRE',11),
	 ('MESES','DESCRIPCION MESES','12','DICIEMBRE',12),
	 ('MONEDA','TIPO MONEDA DE CAMBIO','USD','DOLAR',2),
	 ('MONEDA','TIPO MONEDA DE CAMBIO','BOB','BOLIVIANO',1),
	 ('TIPO CIERRE','TIPO DE CIERRE CONTABLE','CIR','CIERRE DE RESULTADOS',1),
	 ('TIPO CIERRE','TIPO DE CIERRE CONTABLE','CIB','CIERRE DE BALANCE',2),
	 ('TIPO COMPROBANTES CONTABLE','TIPO DE COMPROBANTES DE REGISTRO CONTABLE','CD','DIARIO',1),
	 ('TIPO COMPROBANTES CONTABLE','TIPO DE COMPROBANTES DE REGISTRO CONTABLE','TR','TRASPASO',2),
	 ('TIPO COMPROBANTES CONTABLE','TIPO DE COMPROBANTES DE REGISTRO CONTABLE','GA','GASTO',3),
	 ('TIPO COMPROBANTES CONTABLE','TIPO DE COMPROBANTES DE REGISTRO CONTABLE','IN','INGRESO',4),
	 ('TIPO MOVIMIENTO','TIPO DE MOVIMIENTO DE LOS REGISTROS CONTABLES','DB','DEBE',1),
	 ('TIPO MOVIMIENTO','TIPO DE MOVIMIENTO DE LOS REGISTROS CONTABLES','HB','HABER',2);


INSERT INTO administracion.entidad_dependencia (id_entidad,id_dependencia) VALUES
	 (1,2);


INSERT INTO configuraciones.gestion (gestion,fecha_inicio,fecha_fin) VALUES
	 (2025,'2025-01-01','2025-12-31'),
	 (2026,'2026-01-01','2026-12-31');



INSERT INTO contabilidad.plancuentas (codigo,sigla,descripcion,nivel,orden,padre,ruta,codigo_cuenta) VALUES
	 ('1','ACT','ACTIVO',1,NULL,0,'0','1'),
	 ('2','PA','PASIVO',1,NULL,0,'0','2'),
	 ('3','PTR','PATRIMONIO',1,NULL,0,'0','3'),
	 ('6','CD','CUENTAS DE ORDEN DEUDORAS',1,NULL,0,'0','6'),
	 ('7','CA','CUENTAS DE ORDEN ACREEDORAS',1,NULL,0,'0','7'),
	 ('4','CI','CUENTAS DE INGRESO',1,NULL,0,'0',NULL),
	 ('5','CE','CUENTAS EGRESO',1,NULL,0,'0',NULL),
	 ('9','OCR','OTRAS CUENTAS DE RESULTADOS',1,NULL,0,'0',NULL);
